site_name: BASALT
repo_url: https://github.com/EMBL-PKU/BASALT
site_author: "Zhaorui Jiang"
copyright: "Copyright &copy; PKU EMBL Lab 2025"

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Installation: installation.md
  - Usage: usage.md
  - Tutorial: tutorial.md
  - Pipeline: pipeline.md
  - Output Files: output.md
  - FAQ: faq.md
  - Release Notes: Release_notes.md
  - API Reference: api/index.md

plugins:
  - mkdocs-jupyter
  - glightbox
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - search:
      lang: en

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/ico.png
  favicon: img/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css
