#!/usr/bin/env python3

"""Adapters for optional BASALT candidate binners."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence

from Bio import SeqIO


def _run(command: Sequence[object], cwd: Path | None = None) -> None:
    """Run an external command and propagate a useful failure to BASALT."""
    rendered = [str(item) for item in command]
    print("CMD: {}".format(" ".join(rendered)))
    try:
        subprocess.run(rendered, cwd=cwd, check=True)
    except FileNotFoundError as exc:
        raise RuntimeError("Required command not found: {}".format(rendered[0])) from exc
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            "Command failed with exit status {}: {}".format(
                exc.returncode, " ".join(rendered)
            )
        ) from exc


def _required_file(path: Path, label: str) -> Path:
    resolved = path.expanduser().resolve()
    if not resolved.is_file():
        raise RuntimeError("{} not found: {}".format(label, resolved))
    return resolved


def _safe_cluster_name(value: str) -> str:
    """Convert an external cluster identifier into a safe filename component."""
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    return cleaned or "unlabelled"


def _write_assigned_bins(
    assembly: Path,
    assignments: Mapping[str, str],
    output_dir: Path,
    prefix: str,
    minimum_size: int = 0,
) -> List[Path]:
    """Materialize cluster assignments as BASALT-compatible FASTA files."""
    if output_dir.exists():
        raise RuntimeError(
            "Optional-binner output already exists: {}. Remove the incomplete "
            "directory or resume from a clean run directory.".format(output_dir)
        )
    output_dir.mkdir(parents=True)

    output_paths: Dict[str, Path] = {}
    with assembly.open("r", encoding="utf-8") as assembly_handle:
        for record in SeqIO.parse(assembly_handle, "fasta"):
            cluster = assignments.get(record.id)
            if cluster is None:
                continue
            safe_cluster = _safe_cluster_name(cluster)
            target = output_paths.setdefault(
                safe_cluster, output_dir / "{}.{}.fa".format(prefix, safe_cluster)
            )
            with target.open("a", encoding="utf-8") as output:
                output.write(">{}\n{}\n".format(record.id, record.seq))

    kept: List[Path] = []
    for target in sorted(output_paths.values()):
        with target.open("r", encoding="utf-8") as target_handle:
            sequence_length = sum(
                len(record.seq) for record in SeqIO.parse(target_handle, "fasta")
            )
        if sequence_length < minimum_size:
            target.unlink()
        elif target.stat().st_size > 0:
            kept.append(target)

    if not kept:
        shutil.rmtree(output_dir)
        raise RuntimeError(
            "The optional binner produced no non-empty FASTA bins meeting the "
            "minimum size of {} bp.".format(minimum_size)
        )
    return kept


def _run_quality_check(
    bin_dir: Path,
    output_prefix: Path,
    num_threads: int,
    qc_software: str,
) -> None:
    if qc_software == "checkm":
        _run(
            [
                "checkm",
                "lineage_wf",
                "-t",
                num_threads,
                "-x",
                "fa",
                bin_dir,
                output_prefix,
            ]
        )
    elif qc_software == "checkm2":
        _run(
            [
                "checkm2",
                "predict",
                "-t",
                num_threads,
                "-i",
                bin_dir,
                "-x",
                "fa",
                "-o",
                output_prefix,
            ]
        )
    else:
        raise ValueError("Unsupported quality-control backend: {}".format(qc_software))


def _short_read_bams(
    assembly_file: str,
    datasets: Mapping[str, Sequence[str]],
    workdir: Path,
) -> List[Path]:
    """Return the coordinate-sorted BAM files generated by BASALT mapping."""
    assembly_group = Path(assembly_file).name.split("_", 1)[0]
    bams = [
        workdir / "{}_DNA-{}_sorted.bam".format(assembly_group, index)
        for index in range(1, len(datasets) + 1)
    ]
    missing = [str(path) for path in bams if not path.is_file()]
    if missing:
        raise RuntimeError(
            "Optional binner requires BASALT's coordinate-sorted BAM files; "
            "missing: {}".format(", ".join(missing))
        )
    return [path.resolve() for path in bams]


def _metabinner_executable() -> Path:
    configured = os.environ.get("METABINNER_HOME")
    candidates: List[Path] = []
    if configured:
        candidates.append(Path(configured).expanduser() / "run_metabinner.sh")
    discovered = shutil.which("run_metabinner.sh")
    if discovered:
        candidates.append(Path(discovered))
    candidates.append(Path(sys.executable).parent / "run_metabinner.sh")

    for candidate in candidates:
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return candidate.resolve()
    raise RuntimeError(
        "An executable run_metabinner.sh was not found. Add it to PATH or set "
        "METABINNER_HOME to the pinned MetaBinner installation directory."
    )


def metabinner(
    assembly_file: str,
    depth_file: str,
    num_threads: int,
    ram: int,
    pwd: str,
    QC_software: str,
) -> None:
    """Run MetaBinner and normalize its cluster assignments for BASALT."""
    del ram  # retained in the public adapter signature for compatibility
    workdir = Path(pwd).resolve()
    assembly = _required_file(workdir / assembly_file, "Assembly")
    depth = _required_file(workdir / depth_file, "Depth profile")
    assembly_label = Path(assembly_file).name
    assembly_stem = Path(assembly_label).stem
    coverage_profile = workdir / "{}_coverage_profile.tsv".format(assembly_label)
    filtered_profile = coverage_profile.with_suffix(".filtered.tsv")

    with depth.open("r", encoding="utf-8") as source, coverage_profile.open(
        "w", encoding="utf-8"
    ) as output:
        for line in source:
            fields = line.rstrip("\n").split("\t")
            selected = fields[:1] + fields[3:] if len(fields) >= 4 else fields
            output.write("\t".join(selected) + "\n")

    gen_kmer = _required_file(
        Path(sys.executable).parent / "gen_kmer.py", "Installed gen_kmer.py"
    )
    _run([sys.executable, gen_kmer, assembly, 1000, 4], cwd=workdir)
    kmer_file = _required_file(
        workdir / "{}_kmer_4_f1000.csv".format(assembly_stem), "K-mer profile"
    )

    with kmer_file.open("r", encoding="utf-8") as source:
        next(source, None)
        retained_contigs = {
            line.split(",", 1)[0].strip() for line in source if line.strip()
        }
    with coverage_profile.open("r", encoding="utf-8") as source, filtered_profile.open(
        "w", encoding="utf-8"
    ) as output:
        header = next(source, None)
        if header is not None:
            output.write(header)
        for line in source:
            if line.split("\t", 1)[0].strip() in retained_contigs:
                output.write(line)
    filtered_profile.replace(coverage_profile)

    executable = _metabinner_executable()
    raw_output = workdir / "{}_metabinner".format(assembly_label)
    _run(
        [
            executable,
            "-a",
            assembly,
            "-o",
            raw_output,
            "-d",
            coverage_profile,
            "-k",
            kmer_file,
            "-t",
            num_threads,
            "-p",
            str(executable.parent) + os.sep,
        ],
        cwd=workdir,
    )

    assignment_file = _required_file(
        raw_output / "metabinner_res" / "metabinner_result.tsv",
        "MetaBinner assignment table",
    )
    assignments: Dict[str, str] = {}
    with assignment_file.open("r", encoding="utf-8") as source:
        for line in source:
            fields = line.rstrip("\n").split("\t")
            if len(fields) >= 2:
                assignments[fields[0]] = fields[1]

    bin_name = "{}_100_metabinner_genomes".format(assembly_label)
    bin_dir = workdir / bin_name
    _write_assigned_bins(assembly, assignments, bin_dir, bin_name)
    _run_quality_check(
        bin_dir,
        workdir / "{}_100_metabinner_checkm".format(assembly_label),
        num_threads,
        QC_software,
    )

    shutil.rmtree(raw_output, ignore_errors=True)
    coverage_profile.unlink(missing_ok=True)
    kmer_file.unlink(missing_ok=True)


def _read_vamb_assignments(output_dir: Path) -> Dict[str, str]:
    candidates = [
        output_dir / "vae_clusters_unsplit.tsv",
        output_dir / "clusters.tsv",
    ]
    table = next((path for path in candidates if path.is_file()), None)
    if table is None:
        raise RuntimeError(
            "VAMB did not produce vae_clusters_unsplit.tsv or clusters.tsv in {}".format(
                output_dir
            )
        )

    assignments: Dict[str, str] = {}
    with table.open("r", encoding="utf-8") as source:
        for line in source:
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 2 or fields[0] in {"clustername", "cluster"}:
                continue
            assignments[fields[1]] = fields[0]
    return assignments


def vamb(
    assembly_file: str,
    datasets: Mapping[str, Sequence[str]],
    num_threads: int,
    pwd: str,
    QC_software: str,
) -> None:
    """Run the VAMB 5 command interface using BASALT's sorted BAM files."""
    workdir = Path(pwd).resolve()
    assembly = _required_file(workdir / assembly_file, "Assembly")
    bams = _short_read_bams(assembly_file, datasets, workdir)
    assembly_label = Path(assembly_file).name
    raw_output = workdir / "{}_vamb".format(assembly_label)
    _run(
        [
            "vamb",
            "bin",
            "default",
            "--outdir",
            raw_output,
            "--fasta",
            assembly,
            "--bamfiles",
            *bams,
            "--minfasta",
            500000,
            "-p",
            num_threads,
        ],
        cwd=workdir,
    )

    assignments = _read_vamb_assignments(raw_output)
    bin_name = "{}_100_vamb_genomes".format(assembly_label)
    bin_dir = workdir / bin_name
    _write_assigned_bins(
        assembly, assignments, bin_dir, bin_name, minimum_size=500000
    )
    _run_quality_check(
        bin_dir,
        workdir / "{}_100_vamb_checkm".format(assembly_label),
        num_threads,
        QC_software,
    )
    shutil.rmtree(raw_output, ignore_errors=True)


def _fasta_files(directory: Path) -> Iterable[Path]:
    for path in sorted(directory.rglob("*")):
        if path.is_file() and path.suffix.lower() in {".fa", ".fna", ".fasta"}:
            yield path


def lorbin(
    assembly_file: str,
    datasets: Mapping[str, Sequence[str]],
    num_threads: int,
    pwd: str,
    QC_software: str,
) -> None:
    """Run the BASALT-compatible LorBin fork and normalize its FASTA bins."""
    workdir = Path(pwd).resolve()
    assembly = _required_file(workdir / assembly_file, "Assembly")
    bams = _short_read_bams(assembly_file, datasets, workdir)
    assembly_label = Path(assembly_file).name
    raw_output = workdir / "{}_lorbin_raw".format(assembly_label)
    command: List[object] = [
        "LorBin",
        "bin",
        "-o",
        raw_output,
        "-fa",
        assembly,
        "-b",
        *bams,
        "--num_process",
        num_threads,
    ]
    if len(bams) > 1:
        command.append("--multi")
    _run(command, cwd=workdir)

    source_bins = list(_fasta_files(raw_output))
    if not source_bins:
        raise RuntimeError("LorBin produced no FASTA bins in {}".format(raw_output))

    bin_name = "{}_100_lorbin_genomes".format(assembly_label)
    bin_dir = workdir / bin_name
    if bin_dir.exists():
        raise RuntimeError("Optional-binner output already exists: {}".format(bin_dir))
    bin_dir.mkdir(parents=True)
    for index, source in enumerate(source_bins, start=1):
        target = bin_dir / "{}.{}.fa".format(bin_name, index)
        shutil.copy2(source, target)

    _run_quality_check(
        bin_dir,
        workdir / "{}_100_lorbin_checkm".format(assembly_label),
        num_threads,
        QC_software,
    )
    shutil.rmtree(raw_output, ignore_errors=True)


def extra_binner(
    binner: str,
    datasets: Mapping[str, Sequence[str]],
    assembly_file: str,
    depth_file: str,
    num_threads: int,
    ram: int,
    pwd: str,
    QC_software: str,
) -> List[str]:
    """Dispatch one optional adapter and return its normalized output folder."""
    if binner == "m":
        metabinner(
            assembly_file, depth_file, num_threads, ram, pwd, QC_software
        )
        folder = "{}_100_metabinner_genomes".format(Path(assembly_file).name)
    elif binner == "v":
        vamb(assembly_file, datasets, num_threads, pwd, QC_software)
        folder = "{}_100_vamb_genomes".format(Path(assembly_file).name)
    elif binner == "l":
        lorbin(assembly_file, datasets, num_threads, pwd, QC_software)
        folder = "{}_100_lorbin_genomes".format(Path(assembly_file).name)
    else:
        raise ValueError(
            "Unknown extra binner {!r}; expected m, v, or l.".format(binner)
        )
    return [folder]
